/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.demo.gui;

import com.demo.bo.CheckBO;
import com.demo.entity.User;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Tran Minh Quang
 */
public class LoginPanel extends javax.swing.JFrame {
    /**
     * Creates new form LoginPanel
     * @param userList
     */
    public LoginPanel(ArrayList<User> userList) {
        initComponents();
//        mainPanel.setSize(450, 210);
        addListener(userList);
    }
    
    public JPanel getMainPanel() {
        return mainPanel;
    }

    private void addListener(ArrayList<User> userList) {
        btnRegister.addActionListener((ActionEvent e) -> {
            ClientGUI.getInstance().nextStackPanel(new RegisterPanel(userList).getMainPanel());
        });
        
        btnLogin.addActionListener((ActionEvent e) -> {
            String username = txtUserName.getText();
            String pass = txtPass.getText();
            User user = new User(username, pass);
            if (!CheckBO.isUserName(username)) {
                JOptionPane.showMessageDialog(LoginPanel.this, 
                        "Username must contain only letters and digits, have at least 6 characters and maximum 16 characters");
                return;
            }
            if (!CheckBO.isPassWord(pass)) {
                JOptionPane.showMessageDialog(LoginPanel.this, 
                        "Password must contains at least 1 Uppercase Letter, 1 digit, 1 special letter and 8 characters");
                return;
            }
            if (CheckBO.isMatch(userList, user)) {
                ClientGUI.getInstance().nextStackPanel(new ChatGUI(user).getMainPanel());
                ClientGUI.getInstance().setSize(400, 350);
//                    JOptionPane.showMessageDialog(LoginPanel.this, "Login successful");
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panelCenter = new javax.swing.JPanel();
        panelUsername = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        panelPassword = new javax.swing.JPanel();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        panelButton = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblTitle.setText("Login to Chat Application");
        topPanel.add(lblTitle);

        mainPanel.add(topPanel, java.awt.BorderLayout.PAGE_START);

        panelCenter.setLayout(new java.awt.GridLayout(3, 0, 5, 0));

        lblUserName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblUserName.setText("UserName");
        panelUsername.add(lblUserName);

        txtUserName.setColumns(20);
        txtUserName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        panelUsername.add(txtUserName);

        panelCenter.add(panelUsername);

        lblPass.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblPass.setText("PassWord");
        panelPassword.add(lblPass);

        txtPass.setColumns(20);
        txtPass.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        panelPassword.add(txtPass);

        panelCenter.add(panelPassword);

        btnLogin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnLogin.setText("Login");
        panelButton.add(btnLogin);

        btnRegister.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRegister.setText("Register");
        panelButton.add(btnRegister);

        panelCenter.add(panelButton);

        mainPanel.add(panelCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JPanel panelUsername;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
