/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.demo.gui;

import com.demo.bo.CheckBO;
import com.demo.entity.User;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Tran Minh Quang
 */
public class RegisterPanel extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPanel
     * @param userList
     */
    public RegisterPanel(ArrayList<User> userList) {
        initComponents();
//        mainPanel.setSize(450, 270);
        addListener(userList);
    }
    
    public JPanel getMainPanel() {
        return mainPanel;
    }
    
    private void addListener(ArrayList<User> userList) {
        btnRegister.addActionListener((ActionEvent e) -> {
            String username = txtUser.getText();
            String name = txtName.getText();
            String pass = new String(txtPass.getPassword());
            String repass = new String(txtRePass.getPassword());
            if (!CheckBO.isName(name)) {
                JOptionPane.showMessageDialog(RegisterPanel.this, 
                        "Name must contain only letters and white space and at least 6 character");
                return;
            }
            if (!CheckBO.isUserName(username)) {
                JOptionPane.showMessageDialog(RegisterPanel.this, 
                        "Username must contain only letters and digits, have at least 6 characters and maximum 16 characters");
                return;
            }
            if (!CheckBO.isPassWord(pass)) {
                JOptionPane.showMessageDialog(RegisterPanel.this, 
                        "Password must contains at least 1 Uppercase Letter, 1 digit, 1 special letter and 8 characters");
                return;
            }
            if (!repass.equals(pass)) {
                JOptionPane.showMessageDialog(RegisterPanel.this, 
                        "Re-password not match!");
                return;
            }
            User user = new User(username, pass, CheckBO.normalForm(name));
            if (!CheckBO.exists(userList, user)) {
                userList.add(user);
                JOptionPane.showMessageDialog(RegisterPanel.this, 
                        "Registered successful!");
            } else JOptionPane.showMessageDialog(RegisterPanel.this, 
                    "This user already exists");
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panelCenter = new javax.swing.JPanel();
        namePanel = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        panelUser = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        panelPass = new javax.swing.JPanel();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        panelPassAgain = new javax.swing.JPanel();
        lblPass2 = new javax.swing.JLabel();
        txtRePass = new javax.swing.JPasswordField();
        panelButton = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblTitle.setText("Register");
        titlePanel.add(lblTitle);

        mainPanel.add(titlePanel, java.awt.BorderLayout.PAGE_START);

        panelCenter.setLayout(new java.awt.GridLayout(5, 0, 5, 0));

        lblName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblName.setText("YourName");
        namePanel.add(lblName);

        txtName.setColumns(20);
        txtName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        namePanel.add(txtName);

        panelCenter.add(namePanel);

        lblUser.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblUser.setText("UserName");
        panelUser.add(lblUser);

        txtUser.setColumns(20);
        txtUser.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        panelUser.add(txtUser);

        panelCenter.add(panelUser);

        lblPass.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblPass.setText("PassWord");
        panelPass.add(lblPass);

        txtPass.setColumns(20);
        txtPass.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        panelPass.add(txtPass);

        panelCenter.add(panelPass);

        lblPass2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblPass2.setText("Re-Pass  ");
        panelPassAgain.add(lblPass2);

        txtRePass.setColumns(20);
        txtRePass.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        panelPassAgain.add(txtRePass);

        panelCenter.add(panelPassAgain);

        btnRegister.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRegister.setText("Register");
        panelButton.add(btnRegister);

        panelCenter.add(panelButton);

        mainPanel.add(panelCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPass2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel namePanel;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelPass;
    private javax.swing.JPanel panelPassAgain;
    private javax.swing.JPanel panelUser;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtRePass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
